### ISSUE TITLE
Separate SCSS file so it can be imported/modified by app

### ISSUE THREAD

**Issue by tomgruszowski** [uiuniversal/ngu-carousel#100]
Most UI frameworks separate the SCSS file so the consumer of module is able to apply more customization (see ng material/bootstrap). In the case of a carousel this is definitely desirable.

**Comment by sheikalthaf** [comment]
@tomgruszowski Sure will seprate the css for customization. Thanks

**Comment by tomgruszowski** [comment]
Thank you, might want to separate the visual from functional scss as well. ie padding:10px is not functional. Some libraries make a core.scss and a theme.scss, but that's cherry on top of cake :) ... any scss is good.
