### ISSUE TITLE
[Bug] Prev & Next button doesn't update the bullet points

### ISSUE THREAD

**Issue by luchillo17** [uiuniversal/ngu-carousel#102]
When clicking the Prev & Next button, the slides animate accordingly but the bullet points below doesn't.

Maybe forgot to trigger the bullet change detection? i think so because they update as soon as i click in the content.

**Comment by luchillo17** [comment]
Very likely a change detection issue, i see the change detector ref marking for check only in 4 parts, in theory you shouldn't need it when on click, but it's weird to me that it get's updated only in the next interaction.

Also seems to happen with the drag actions, if i drag to the right for the next slide, i get the same issue.

**Comment by sheikalthaf** [comment]
@luchillo17 Hi,

I tried to reproduce it but no luck. Will you please create a stackblitz with the issue.

Thanks

**Comment by luchillo17** [comment]
I think it's very likely me not having the latest version, still with Angular 5, update schedule is for next month.
