### ISSUE TITLE
ngu-item with partial previous and after

### ISSUE THREAD

**Issue by amanecer2** [uiuniversal/ngu-carousel#105]
does this library can supply partial view on the side? like 
![image](https://user-images.githubusercontent.com/8917429/46605715-2f144c80-cb03-11e8-9830-da0b69a5d779.png)
thanks

**Comment by sheikalthaf** [comment]
@amanecer2 Hi,

Working on this feature and also carousel looping. Once it goes to beta will let you know. I'm working on my free time.

Thanks

**Comment by Herm9111** [comment]
If you override the max width directly on the ngtile element (from 100% to whatever value you want) You can 'hack' this.

<ngu-tile *nguCarouselDef="let item; let i = index; let ani = animate" style="max-width: 250px;">

By the way, Thank sheikalthaf for your work, I'm loving this component.

Regards!
