### ISSUE TITLE
Issue when images and video loaded into ngu- carousel

### ISSUE THREAD

**Issue by sojimon** [uiuniversal/ngu-carousel#112]
Hi, I tried to load images and videos into ngu-carousel. And I found two issues.

1. If the video is first in the array then images, there is no issue.And carousel loads.But when the video comes after images, the video will comes over the images.

2. If the array contain only video , it does not loads.

Note:- In my case the video is from Vimeo.

**Comment by sheikalthaf** [comment]
Hi,



Will you please create a stackblitz repo with the issue. It will be helpfull to find the bug.



Thanks
