### ISSUE TITLE
Carousel autoplay stops when scrolling event occurs

### ISSUE THREAD

**Issue by AshotStdev** [uiuniversal/ngu-carousel#113]
Angular version 6.1.10

**Comment by AshotStdev** [comment]
@sheikalthaf Hello, i'm using the latest version.

**Comment by AshotStdev** [comment]
@sheikalthaf here's a video https://drive.google.com/file/d/1gxrHTtzi2x_YkouHR131cIVPBx47SfUm/view

**Comment by sheikalthaf** [comment]
@AshotStdev This is not an issue it is a feature. When carousel not in viewport the carousel will stop automatically. But i think your carousel is very big in height that's y it is stopped on scroll will fix this based on height

Thanks for reporting

**Comment by AshotStdev** [comment]
@sheikalthaf carousel is stopping in case of any height, is there any options to stop carousel only on hover?

**Comment by AshotStdev** [comment]
> @AshotStdev This is not an issue it is a feature. When carousel not in viewport the carousel will stop automatically. But i think your carousel is very big in height that's y it is stopped on scroll will fix this based on height
> 
> Thanks for reporting


@sheikalthaf  In fact, it does not work as you say, but rather, it stops when it is IN viewport.

**Comment by duprez** [comment]
Any news?

**Comment by JuanMME** [comment]
Same problem here, my carousel is not in view mode when you load the page, but it will auto play regardless. And then when you scroll down where the carousel is it stops, but if you hover over it it fixes itself.

**Comment by pramith-mdosl** [comment]
I added two carousel in top of page and bottom of page..both auto rotate feature enabled...But auto rotate works only to the top slider. How could i solve this issue? Any Suggestions?

**Comment by nagavenkateshK** [comment]
Dont use ngu carousal inside cards or columns ... It resolved my issue with auto play
