### ISSUE TITLE
angular 7 version

### ISSUE THREAD

**Issue by sajidali2444** [uiuniversal/ngu-carousel#118]
can someone help me how to resolve Generic type 'NguCarousel<T>' requires 1 type argument(s) error?
i try to use any instead of T, but it gives errors more.
i want to implement this example from demos **Tile-WithLoop and Animation**

**Comment by Cyw00d** [comment]
You can add typing to NguCarousel<T> < T is for typing. You can put the config typing here (NguCarouselConfig) or if you have a different config you can put 'any' there, so it becomes NguCarousel<any>

**Comment by harellevy** [comment]
"prev" and "next" states still have issues. calculation is not correct.

**Comment by sheikalthaf** [comment]
@harellevy I'm working on next major version so i have no time to fix this.

Also I'm currently very busy working on my company projects. Once i will be free i try to publish the builds asap
