### ISSUE TITLE
Reset status when dataSource is updated

### ISSUE THREAD

**Issue by kstolk** [uiuniversal/ngu-carousel#119]
Is it possible to reset to the first 'slide' when dataSource has changed? I'm using dyanmic data (with tabs) and when I press the first tab that has 2 items and slide to the 2nd... Then I press the 2nd tab that has only 1 item you won't see anything because it is on the 2nd slide with only 1 item.

**Comment by Cyw00d** [comment]
That would be great, when could this be implemented?
