### ISSUE TITLE
Scrolling right problem

### ISSUE THREAD

**Issue by pantonis** [uiuniversal/ngu-carousel#12]
Hi,

When scrolling to right carousel behavior breaks. See the moving gif below:

![carousel](https://user-images.githubusercontent.com/3295086/36023412-00a2f1d4-0d95-11e8-8643-1383553c6048.gif)

At first I though that I was adding empty items to the collection of items. But when I debugged this was not the case.

This is my code

```
<ngu-carousel [inputs]="typesCarousel">
	<ngu-tile NguCarouselItem *ngFor="let type of types" style="width:auto!important;padding:5px!important;">
		<div class="btn-group" data-toggle="buttons">
			<label class="btn" [ngClass]="(type.Selected === true) ? 'btn-selected' : 'btn-not-selected'" (click)="dataService.typeClicked(type)">
				<input type="checkbox" class="toggle" [value]="type.Name">{{type.Name}}
			</label>
		</div>
	</ngu-tile>

	<span NguCarouselPrev class='carousel-prev-button'>
		<i class="fa fa-arrow-left" aria-hidden="true"></i>
	</span>
	<span NguCarouselNext class='carousel-next-button'>
		<i class="fa fa-arrow-right" aria-hidden="true"></i>
	</span>
</ngu-carousel>
```

**Comment by pantonis** [comment]
Any feedback?

**Comment by puneetg1983** [comment]
I was also facing this issue but when I gave a fixed width in grid, the issue went away
`grid: { xs:0, sm:0, md:0, lg:0, all:135}`

might wanna give that a try.

**Comment by pantonis** [comment]
fixed width is not good as for different resolutions is not gonna work
