### ISSUE TITLE
after upgrade animation 'lazy' not working

### ISSUE THREAD

**Issue by harellevy** [uiuniversal/ngu-carousel#120]
upgrade angular from 6.0.9 to 6.1.0, updated ngu-carousel and make it work but animation lazy doesn't works.

**Comment by sheikalthaf** [comment]
@harellevy Hi,

Yes we have some element ref issue to animate the item in latest version, but it is temporary I'm working on custom animation where you can able to animate the item yourself. Once it is complete let you know.

Thanks
