### ISSUE TITLE
until latest version you could add static sliding item in addition to *ngFor, with *nguCarouselDef its not possible

### ISSUE THREAD

**Issue by harellevy** [uiuniversal/ngu-carousel#121]
now with the [dataSource] attribute and *nguCarouselDef template for the loop i cannot longer add additional static content as another ngu-item.
it just ignores it.
please advice.

**Comment by harellevy** [comment]
currently as a workaround i use a ng-container in the ngu-item as follow:

<ngu-item NguCarouselItem *nguCarouselDef="let item">
      <ng-container *ngIf="item; else viewMoreBox">
        <app-song-item [item]="item"></app-song-item>
      </ng-container>
      <ng-template #viewMoreBox>
        <div class="custom-carousel-item-box" (click)="myPlaylist(channel._id)">
        view more
        </div>
      </ng-template>
    </ngu-item>

**Comment by F3LENYR** [comment]
Nice workaround ! I hope @sheikalthaf will solve this problem in next release ;)

**Comment by mtinnes** [comment]
@sheikalthaf any plans to re-enable the use of static items?
