### ISSUE TITLE
Grid does not work as expected

### ISSUE THREAD

**Issue by pantonis** [uiuniversal/ngu-carousel#124]
Why do we have to specify grid. Carousel should be auto calculating how many items should be shown based on screen size.
The way it works now it is useless. If I specify 3 items for lg and each item is not the same size it leaves huge white spaces 

![image](https://user-images.githubusercontent.com/3295086/48194719-79812700-e356-11e8-8977-cda8dd5f0719.png)

**Comment by sheikalthaf** [comment]
@pantonis sorry to hear this. The carousel only set width for the .item class which is showing in your screenshot. Make the inner element to block size so that it will take a parent size and your problem will be solved.

Thanks
