### ISSUE TITLE
Wrong behaviors when having less items than the grid size

### ISSUE THREAD

**Issue by adrienlamotte** [uiuniversal/ngu-carousel#125]
Hello,

Here is a StackBlitz : https://stackblitz.com/edit/ngu-carousel-ng6-dgas5v

You can see that the `myCarousel.isLast` is not set to true, and there is some weird behaviors when you resize the window (so the grid change). For exemple if you go to xs grid, go to slide 3, and resize the windows to md grid, you're stuck.

Thank you for your work :-)

**Comment by sheikalthaf** [comment]
@adrienlamotte thanks for reporting will check and fix, but it is not a show stopper.

**Comment by sanyashvets** [comment]
so, is it fixed?
