### ISSUE TITLE
Anyone got this working for Angular 7.

### ISSUE THREAD

**Issue by yogeshbansal** [uiuniversal/ngu-carousel#128]
I tried to use this component is angular 7. But getting many errors. Example given is not working in angular 7

**Comment by harellevy** [comment]
No support for angular 7?

**Comment by WillHall** [comment]
Works for me in ng7

in component:
```
import { NguCarousel, NguCarouselConfig } from '@ngu/carousel';
```

in @Component
```
  @ViewChild('carousel') carousel: NguCarousel<any>;
  public carouselOne: NguCarouselConfig;
```


in init
```
    this.carouselOne = {
      grid: { xs: 1, sm: 1, md: 1, lg: 1, all: 0 },
      slide: 1,
      speed: 10,
      interval: {
        timing: 3000,
        initialDelay: 0
      },
      point: {
        visible: false
      },
      load: 5,
      touch: false,
      loop: false,
      custom: 'banner'
    };
```

in template:
```
  <ngu-carousel #carousel [inputs]="carouselOne" [dataSource]="data">
    <ngu-tile *nguCarouselDef="let tile; let i = index; let lastTile = last">
      ...
    </ngu-tile>
  <ngu-carousel
```

hth

**Comment by SiddharthaSGogoi** [comment]
> Works for me in ng7
> 
> in component:
> 
> ```
> import { NguCarousel, NguCarouselConfig } from '@ngu/carousel';
> ```
> in @ Component export
> 
> ```
>   @ViewChild('carousel') carousel: NguCarousel<any>;
>   public carouselOne: NguCarouselConfig;
> ```
> in init
> 
> ```
>     this.carouselOne = {
>       grid: { xs: 1, sm: 1, md: 1, lg: 1, all: 0 },
>       slide: 1,
>       speed: 10,
>       interval: {
>         timing: 3000,
>         initialDelay: 0
>       },
>       point: {
>         visible: false
>       },
>       load: 5,
>       touch: false,
>       loop: false,
>       custom: 'banner'
>     };
> ```
> in template:
> 
> ```
>   <ngu-carousel #carousel [inputs]="carouselOne" [dataSource]="data">
>     <ngu-tile *nguCarouselDef="let tile; let i = index; let lastTile = last">
>       ...
>     </ngu-tile>
>   <ngu-carousel
> ```
> hth

Still comes up with the error `Cannot find  name 'ViewChild'`

**Comment by angelserranoperez** [comment]
Have you put the ViewChild Import?
import {ViewChild} from '@angular/core';

**Comment by harellevy** [comment]
i have issues with "prev" and "next" states.

**Comment by SiddharthaSGogoi** [comment]
> Have you put the ViewChild Import?
> import {ViewChild} from '@angular/core';

I did and it worked but the carousel is not what I expected. I found a replacement in https://github.com/bfwg/ngx-drag-scroll if anybody is looking for a working angular 7 carousel.

**Comment by harellevy** [comment]
> > Have you put the ViewChild Import?
> > import {ViewChild} from '@angular/core';
> 
> I did and it worked but the carousel is not what I expected. I found a replacement in https://github.com/bfwg/ngx-drag-scroll if anybody is looking for a working angular 7 carousel.

I tried using ngx-drag-scroll and found this repo which i find much more nice:
https://github.com/ZouYouShun/ngx-hm-carousel/

**Comment by lujakob** [comment]
I didn't get the example running with Angular 7 in 1,5 hours. 
But I got @harellevy 's repo https://github.com/ZouYouShun/ngx-hm-carousel/ up and running in 5 mins

**Comment by cnscorpions** [comment]
not work with ng7, i have have a try at https://github.com/ZouYouShun/ngx-hm-carousel/

**Comment by macwac** [comment]
> Works for me in ng7
> 
> in component:
> 
> ```
> import { NguCarousel, NguCarouselConfig } from '@ngu/carousel';
> ```
> in @ Component export
> 
> ```
>   @ViewChild('carousel') carousel: NguCarousel<any>;
>   public carouselOne: NguCarouselConfig;
> ```
> in init
> 
> ```
>     this.carouselOne = {
>       grid: { xs: 1, sm: 1, md: 1, lg: 1, all: 0 },
>       slide: 1,
>       speed: 10,
>       interval: {
>         timing: 3000,
>         initialDelay: 0
>       },
>       point: {
>         visible: false
>       },
>       load: 5,
>       touch: false,
>       loop: false,
>       custom: 'banner'
>     };
> ```
> in template:
> 
> ```
>   <ngu-carousel #carousel [inputs]="carouselOne" [dataSource]="data">
>     <ngu-tile *nguCarouselDef="let tile; let i = index; let lastTile = last">
>       ...
>     </ngu-tile>
>   <ngu-carousel
> ```
> hth

thx, it's working on Angular 7.2.12

**Comment by santoshyadav198613** [comment]
We support Angular 9 now.
