### ISSUE TITLE
found version 4, expected 3

### ISSUE THREAD

**Issue by missaouiaymen** [uiuniversal/ngu-carousel#131]
ERROR in Error: Metadata version mismatch for module 
.../node_modules/@ngu/carousel/ngu-carousel.d.ts, found version 4, expected 3, resolving symbol AppModule in /app.module.ts

**Comment by sheikalthaf** [comment]
@missaouiaymen looking weird. never faced this kind of issue. any reproducing steps

**Comment by roik7** [comment]
@missaouiaymen -  did you manage to run it?
@sheikalthaf -  having the same issue
my angular version: 4.1.3
basically did the same thing WillHall recommended in issue: https://github.com/sheikalthaf/ngu-carousel/issues/128
and than I get the following error:
node_modules/@ngu/carousel/ngu-carousel.d.ts, found version 4, expected 3, resolving symbol AppModule

**Comment by sheikalthaf** [comment]
@missaouiaymen @roik7 The current version is only support angular version >= 6. because it is using angular 6 library building.

**Comment by roik7** [comment]
@sheikalthaf - thanks for the response.
is there a prior version that does support angular 4?
