### ISSUE TITLE
Right arrow is enabled even if there are no more elements to scroll

### ISSUE THREAD

**Issue by shiva-tammina** [uiuniversal/ngu-carousel#134]
I have tried with different number of tiles, Following are the scenarios:
1. Total number of tiles are more than the number of tiles which should be shown at a time.
    > In the above scenario Carousel is working fine.
2. Total number of tiles are lesser than the number of tiles which should be shown at a time.
    > In this scenario Right side arrow is getting highlighted even though there are no items to scroll(carousel.isLast value is displaying wrong).

I have debugged this in stackblitz.

Please check below screenshot.

![image](https://user-images.githubusercontent.com/40623542/50470388-43ffce00-09d6-11e9-80c1-4a8798bfdb99.png)

**Comment by sanketmaru** [comment]
Is there a fix available for this ?

**Comment by arucastillo** [comment]
hello, Is there a fix available for this?
