### ISSUE TITLE
Error On installing

### ISSUE THREAD

**Issue by workforfilmsGithub** [uiuniversal/ngu-carousel#139]
I am trying to install and getting this error 

apples-iMac-4:Fuse-v7.0.1-skeleton apple$ npm install @ngu/carousel -save

npm WARN @agm/core@1.0.0-beta.5 requires a peer of @angular/common@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @agm/core@1.0.0-beta.5 requires a peer of @angular/core@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngrx/effects@6.1.2 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngrx/entity@7.0.0 requires a peer of @ngrx/store@7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngrx/router-store@6.1.2 requires a peer of @angular/common@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngrx/router-store@6.1.2 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngrx/router-store@6.1.2 requires a peer of @angular/router@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngrx/store@6.1.2 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @swimlane/ngx-charts@10.0.0 requires a peer of d3@^4.10.2 but none is installed. You must install peer dependencies yourself.
npm WARN @swimlane/ngx-dnd@6.0.0 requires a peer of @types/dragula@^2.1.33 but none is installed. You must install peer dependencies yourself.

npm ERR! Cannot read property '0' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/apple/.npm/_logs/2019-01-19T11_02_37_482Z-debug.log
apples-iMac-4:Fuse-v7.0.1-skeleton apple$ npm install @ngu/carousel --save
npm WARN @agm/core@1.0.0-beta.5 requires a peer of @angular/common@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @agm/core@1.0.0-beta.5 requires a peer of @angular/core@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngrx/effects@6.1.2 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngrx/entity@7.0.0 requires a peer of @ngrx/store@7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngrx/router-store@6.1.2 requires a peer of @angular/common@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngrx/router-store@6.1.2 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngrx/router-store@6.1.2 requires a peer of @angular/router@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngrx/store@6.1.2 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @swimlane/ngx-charts@10.0.0 requires a peer of d3@^4.10.2 but none is installed. You must install peer dependencies yourself.
npm WARN @swimlane/ngx-dnd@6.0.0 requires a peer of @types/dragula@^2.1.33 but none is installed. You must install peer dependencies yourself.

npm ERR! Cannot read property '0' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/apple/.npm/_logs/2019-01-19T12_13_52_218Z-debug.log

**Comment by santoshyadavdev** [comment]
this is not related to this library.
