### ISSUE TITLE
IE 11 - ngu carousel is broken

### ISSUE THREAD

**Issue by nabeelsalam** [uiuniversal/ngu-carousel#140]
ngu-carousel is working fine in Chrome, Edge, Firefox. but in IE 11, box width calculation seems to be wrong.
Tested the demo app in IE 11. Please find the screenshot below.

![image](https://user-images.githubusercontent.com/15714900/51998744-39c66900-2487-11e9-89a8-7b8c5f699f63.png)

**Comment by ankitkhedekar** [comment]
Facing the same issue. Any possible workarounds?

**Comment by ankitkhedekar** [comment]
It seems to be some issue with the padding applied to the ngu-tile. Moving the padding from there to one of its inner div seems to fix the problem

**Comment by jsdevtom** [comment]
#### Workaround:
```
// Fix ie11 wrong spacing
:host ::ng-deep ngu-carousel ngu-tile {
    max-width: 33.3333%; // or what ever you configured 
}
```
Make sure you account for media queries as well though

**Comment by santoshyadavdev** [comment]
please check if workaround works.
