### ISSUE TITLE
A readable example

### ISSUE THREAD

**Issue by noncom** [uiuniversal/ngu-carousel#147]
Looking into the usage example hits you with a barely formatted wall of text for the carousel template, which is very hard to read, especially when you at first jump between it and the component JS code a lot to see what goes where.

Could you please extract the template into a separate code block and apply formatting and language highlight to it?

**Comment by sheikalthaf** [comment]
Hi @noncom ,

Please check [this demo](https://stackblitz.com/edit/ngu-carousel-demo?file=src%2Fapp%2Fstatic%2Fstatic.component.html) for the usage of this carousel

**Comment by tayambamwanza** [comment]
@sheikalthaf Thanks, that's much better, but still hard to grasp for a beginner, the best would just be the config object, followed by the array of images, and the template binding.

Just those core concepts would be perfect, adding change detection and everything else can come in as an advanced part of documentation

**Comment by tayambamwanza** [comment]
I think an example with only the simple example as well, leave out routing etc, just an isolated simple carousel.

Thank you for all the hard work, I can't even begin to imagine how much work you've put in to this, just to help others, I'm deeply grateful.

**Comment by tayambamwanza** [comment]
Something as simple as this would be very welcoming

https://stackblitz.com/edit/ngu-carousel-demo-n3rfvf

Then later in the docs you can add more complicated examples
