### ISSUE TITLE
Start with dynamic index

### ISSUE THREAD

**Issue by soniyaBisht04** [uiuniversal/ngu-carousel#160]
I want to start my carousel with a given index, not always from 0.
Is it achievable?

**Comment by stevearagonsite** [comment]
You should be initialize this component with ngAfterViewInit and use ```this.myCarousel.moveTo(index);``` or user this function when activated the view.
I had this same problem when initialize and i solved with this solution.

**Comment by svralkar30** [comment]
moveToSlide() accept the index of the tile.

```
  moveToSlide(index) {
    this.carousel.moveToSlide(this.carouselToken, index, false);
  }
```

**Comment by sheikalthaf** [comment]
@santoshyadav198613 it is possible to add this an input so that when we intiative the carousel we can start with the given index. What's your thoughts?

**Comment by santoshyadav198613** [comment]
I would not suggest implementing this, I have never seen any carousel doing it, if moveToSlide works it should be used.

**Comment by sheikalthaf** [comment]
You are right, then we can close this now.
