### ISSUE TITLE
Upgrade Angular 8 

### ISSUE THREAD

**Issue by fasfelipe** [uiuniversal/ngu-carousel#163]
Hey Folks,

Is there any tracking to update to Angular 8? I saw the support to Angular 7 is already in place but structure changes like `ViewChild()` is blocking developments on Angular 8. 

Is there any hack to use this using Angualr 8?

**Comment by AntoineJeanDev** [comment]
I use it in Angular 8, still works (95% fine i'd say)

**Comment by kolkov** [comment]
> I use it in Angular 8, still works (95% fine i'd say)
> 
> But an update for Angular 8 would be very much appreciated !

Ivy not working now with `ngu-carousel` :(

**Comment by DanVLopes** [comment]
Now we have a pull request for this. Take a look and let's make it work
https://github.com/sheikalthaf/ngu-carousel/pull/164

**Comment by kolkov** [comment]
@fasfelipe I try to use your fork directly from Github.
```
ERROR in Unable to write a reference to NguCarousel in D:/Go/inframe/ui/node_modules/@ngu/carousel/projects/carousel/src/lib/ngu-carousel/ngu-carousel.component.ts from D:/Go/inframe/ui/node_modules/@ngu/carousel/projects/carousel/src/lib/ngu-carousel.module.ts
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
i ｢wdm｣: Failed to compile.
```
