### ISSUE TITLE
Stop slideing when touched

### ISSUE THREAD

**Issue by whimzyLive** [uiuniversal/ngu-carousel#166]
h2.Background:
I am using ngu-carousel in my angular app, and is working brilliantly, but now the problem that I am facing is to stop sliding when touched/clicked.

h3.Use Case
I have images and videos inside slider and would like to have auto sliding on initially and when someone clicks/touches (i.e playing a video) slider should stop auto sliding.

h3.Potential solution
ngu-carousel should accept NguCarouselConfig as observable and subscribe to it. May be?

I will be happy to do PR if guided to what else depends on config.

**Comment by dima-gusyatiner** [comment]
I also have issues with the slider when touched,
for me:
- you swipe on the carousel
- it moves a little bit
- the point stops working (no point is selected) 
- swiping doesn't do anything at all
- pressing on a button (next/prev) doesn't work

**Comment by GregKlarecky** [comment]
try putting  event.preventDefault() on dragstart event on your images and moving cdr.detectChanges() to the place where carousel data for dataSource input is initialized. Put ngIf on your carousel wrapper *ngIf="dataSource"
