### ISSUE TITLE
Is there any destroy method?

### ISSUE THREAD

**Issue by hotka** [uiuniversal/ngu-carousel#167]
I have two templates in one component (<ng-template> for mobile and desktop). In mobile template there is carousel, but when I resize window and toggle template to desktop's, I have an issue. How can I destroy carousel?

**Comment by sheikalthaf** [comment]
@hotka Currently there is no destroy method available. Can you post some sample code how you are configuring?

**Comment by arturovt** [comment]
Closing as stale.
