### ISSUE TITLE
Not compatible with Angular Universal

### ISSUE THREAD

**Issue by SushmaThalapaneni** [uiuniversal/ngu-carousel#169]
Hi @sheikalthaf 

When am using @ngu-carousel with angular universal, its throwing the following error.
Angular version - 7.1.4

\node_modules\@ngu\carousel\src\ngu-tile\ngu-tile.component.js:1
import { Component, HostBinding } from '@angular/core';
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)

How can I resolve this as its priority task.

**Comment by santoshyadav198613** [comment]
This is done now try 2.0.3 and you need to use Angular 9
