### ISSUE TITLE
Infinite loop is possible for banners slider????????????????????????????????

### ISSUE THREAD

**Issue by hemanthsp** [uiuniversal/ngu-carousel#17]
Infinite loop is possible for banners slider?

**Comment by hemanthsp** [comment]
give me any suggestion i will also try

**Comment by sheikalthaf** [comment]
@fridolin-koch Hi,

Do you have any idea to make the carousel loop?

**Comment by xXCalleManXx** [comment]
Any solution for this?

**Comment by santoshyadavdev** [comment]
duplicate of  https://github.com/uiuniversal/ngu-carousel/issues/7
