### ISSUE TITLE
this.dataSource is undefined

### ISSUE THREAD

**Issue by Jay-PC** [uiuniversal/ngu-carousel#176]
When following your directions to "Banner with Custom point style", I received an error in the browser console, "this.dataSource is undefined". Is there a complete example with the latest Angular where the carousel is built in HTML and not dynamically built from a function? The one you have under "Banner with Custom point style" does not seem complete.

**Comment by santoshyadav198613** [comment]
Hi @Jay-PC ,
 you can refer to https://github.com/sheikalthaf/ngu-carousel/tree/master/src for a working example.

**Comment by sheikalthaf** [comment]
The readme has older code demos. Need to replace those with stackblitz links.


Sorry for the incorrect readme
