### ISSUE TITLE
ObjectUnsubscribedErrorImpl still showing up

### ISSUE THREAD

**Issue by KingDarBoja** [uiuniversal/ngu-carousel#218]
The fix introduced on #157 still doesn't work as the component still show up the error while being destroyed.

![image](https://user-images.githubusercontent.com/30560560/78037697-80388180-7331-11ea-93bd-7588187f0702.png)

I checked the source code (i.e. fesm2015) and the fix isn't there. Using the latests version (2.0.0)

**From fesm2015 ngu-carousel.js**
```
    ngOnDestroy() {
        // clearInterval(this.carouselInt);
        this.carouselInt && this.carouselInt.unsubscribe();
        this._intervalController$.unsubscribe();
        this.carouselLoad.complete();
        this.onMove.complete();
        /** remove listeners */
        for (let i = 1; i <= 4; i++) {
            const str = `listener${i}`;
            this[str] && this[str]();
        }
    }
```

**Comment by santoshyadav198613** [comment]
Looks like we need to release it, will do it over the weekend.

**Comment by santoshyadav198613** [comment]
Hi @KingDarBoja, can you test with 2.0.2 tag.

**Comment by santoshyadav198613** [comment]
Hi @KingDarBoja ,
Can you confirm if the latest version worked for you?

**Comment by KingDarBoja** [comment]
Can confirm it is gone on 2.0.3. Thanks!
