### ISSUE TITLE
grid information

### ISSUE THREAD

**Issue by pantonis** [uiuniversal/ngu-carousel#22]
What does grid do? In the documentation it says
"xs - mobile, sm - tablet, md - desktop, lg - large desktops, all - fixed width (When you use all make others 0 and vise versa)" but it does not explain what it actually does?

**Comment by sheikalthaf** [comment]
HI,

This carousel is a responsive to css media query. I want to show 1 item in mobile, 3 items in tablet and 4 items in desktop. To achieve this i have defined in bootstrap style grid.

xs - means mobile screen 
sm -Tablet
md - desktop
lg - large desktop
all - means fixed width for item.

**Comment by pantonis** [comment]
@sheikalthaf first of all thanks for your great work. very nice control. all means fix width. If I don't want fixed width but width auto based on the size of the item e.g Car takes less width than Airplane how do I achieve that?

**Comment by sheikalthaf** [comment]
@pantonis  currently carousel doesn't support different width for items. Maybe in future i will include it

**Comment by pantonis** [comment]
@sheikalthaf this missing functionality cause the below bug I think
https://github.com/sheikalthaf/ngu-carousel/issues/12

**Comment by kmturley** [comment]
Looks like there is a fixed width demo here:
https://stackblitz.com/edit/angular-x2m3xa?file=app%2Fapp.component.ts

Using the values:
`grid: {xs: 0, sm: 0, md: 0, lg: 0, all: 130},`
