### ISSUE TITLE
Angular 9 example error

### ISSUE THREAD

**Issue by ElesGergo** [uiuniversal/ngu-carousel#226]
Hello guys,
    
    ERROR in node_modules/@ngu/carousel/lib/ngu-carousel.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of HomeModule, but could not be resolved to an NgModule class.
    
    This likely means that the library (@ngu/carousel) which declares NguCarouselModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
    
    1 export declare class NguCarouselModule {

I am trying to make one of the examples work but I am always getting this issue.

Any suggesstion with this one ?

**Comment by santoshyadav198613** [comment]
Which version are you using, can you delete node_modules and try again once.

**Comment by santoshyadav198613** [comment]
You can test with 2.0.3 with it is related to SSR

**Comment by ElesGergo** [comment]
Seems to work with 2.0.3 Thanks!
