### ISSUE TITLE
How can I subscribe to carousel.

### ISSUE THREAD

**Issue by areg-shahnazaryan** [uiuniversal/ngu-carousel#253]
Hi, I need to subscribe carousel activePoint on my typescript file but I didn't find any subscription.
Can you help me to find solution?

**Comment by sheikalthaf** [comment]
@areg-shahnazaryan Hi, can you please elaborate your use cases. You can have option to listen for carousel move. But not for carousel point.

**Comment by areg-shahnazaryan** [comment]
@sheikalthaf I need call function when carousel item changes without clicking on points or arrows.
So, how can I detect changes when carousel item changes.
I was searching observables to subscribe but I didn't find anything.

**Comment by sheikalthaf** [comment]
@areg-shahnazaryan yog can make use of `onMove` output event in carousel. Which will be triggered on every slide changes. Please refer readme about the details of the events

**Comment by areg-shahnazaryan** [comment]
@sheikalthaf Now I can handle event.
Thank you so much for your response.
