### ISSUE TITLE
Variable width tiles?

### ISSUE THREAD

**Issue by sjgstarz** [uiuniversal/ngu-carousel#26]
Do you have any roadmap plans to add variable width support to this?  I current like how your slider works and I'd love to use it, but variable width support is a requirement for my project.

**Comment by sheikalthaf** [comment]
@sjgstarz It is bit difficult because i have to calculate every width of the tiles before slide also to maintain in responsive. But nothing is impossible. I will try to implement it

**Comment by sjgstarz** [comment]
@sheikalthaf Yeah it's not trivial that's for sure, but it's a great feature.
