### ISSUE TITLE
Specific responsive carousel configurations?

### ISSUE THREAD

**Issue by sjgstarz** [uiuniversal/ngu-carousel#27]
Do you have any roadmap plans to include responsive specific carousel configurations to this component?  More specifically the ability to change the carousel properties like slide, animation or load based on the grid size properties?

**Comment by sheikalthaf** [comment]
@sjgstarz soon it will be added. Request your feature here
Thanks

**Comment by nabeelsalam** [comment]
can we set slide property per viewport config?
