### ISSUE TITLE
nguCarouselDef trackBy item and index value

### ISSUE THREAD

**Issue by suniyal** [uiuniversal/ngu-carousel#295]
Hi,

while using trackBy, the index and item values in the method are coming as undefined. Checking from the ngu carousel method, the values that are needed are _i for index and item for item here -> https://github.com/uiuniversal/ngu-carousel/blob/6d3ce00f8b247733232cbdbe0267ad8d1b66f48c/projects/ngu-carousel/src/lib/ngu-carousel/ngu-carousel.component.ts#L169

instead of item.dataIndex and item.data

is there a way for this to work ?

**Comment by plamoni** [comment]
According to Angular's docs, `IterableDiffer.create(...)`[accepts a `TrackByFunction`](https://angular.io/api/core/IterableDifferFactory#create), so @suniyal is right that the arguments should just be passed into `this.trackBy` as presented by the host function.

I've updated locally and tested to confirm that trackBy is working as expected by:

1. Created a data source that emits an ever-growing list of numbers
2. Created a component that logs when it's created and destroyed and used that in a `<ngu-item>`
3. Confirmed that the existing components are destroyed each time the data source updates
4. Added a trackBy that tracks the items by value
5. Confirmed that the existing components are no longer destroyed on each update

Pull request sent with a fix.
