### ISSUE TITLE
Render problem (blurry)

### ISSUE THREAD

**Issue by esidate** [uiuniversal/ngu-carousel#296]
Hello, I know this package is supposed to be used with images and I would appreciate your help.
In the first slide the elements inside `<ngu-tile></ngu-tile>` are rendered normally 
![image](https://user-images.githubusercontent.com/59918011/89814413-00ba8a80-db3b-11ea-93dc-0207cd7abb8c.png)
but in the other slides the elements become blurry
![image](https://user-images.githubusercontent.com/59918011/89814615-4c6d3400-db3b-11ea-886a-52dfa576d686.png)
here's the code
![image](https://user-images.githubusercontent.com/59918011/89814807-a1a94580-db3b-11ea-8441-e1fa8af38c7d.png)
Thank you in advance.

**Comment by sheikalthaf** [comment]
@esidate can you help me with small repro
