### ISSUE TITLE
[Feature Request] Swipe scrolling rather than paging

### ISSUE THREAD

**Issue by rat-matheson** [uiuniversal/ngu-carousel#305]
Currently on touch devices, if I swipe, I get the next slide (or the next page of slides if there are multiple).  Instead, I would like a way to just have the carousel continue scrolling (and then slowly stop), like when I swipe to scroll vertically on a long webpage.

Scrolling seems more natural and similar to native devices.

**Comment by borriej** [comment]
I also have this feature request. I dont want to be bound by the grid of ngu-carousel.

Is this possible with some config on the current build?

**Comment by rat-matheson** [comment]
At this point, I'm thinking it is probably better to build a control for my own needs.  My plan is to just define cards and put those inside a div that can scroll horizontally.  Seems easy enough.  I'm not going to lazy load but instead have a more button after 8 to 10 cards.  

The other thing I realized is that this kind of side scrolling is great for mobile but terrible for desktop (which is meant for vertical scrolling) so I will define some rules that just switches to a grid for desktop with vertical scrolling.  Perhaps you problem can be solved similarly.

**Comment by pulkitpatel95** [comment]
> At this point, I'm thinking it is probably better to build a control for my own needs. My plan is to just define cards and put those inside a div that can scroll horizontally. Seems easy enough. I'm not going to lazy load but instead have a more button after 8 to 10 cards.
> 
> The other thing I realized is that this kind of side scrolling is great for mobile but terrible for desktop (which is meant for vertical scrolling) so I will define some rules that just switches to a grid for desktop with vertical scrolling. Perhaps you problem can be solved similarly.

Hi, did you find a way to do this ?
I also have the same requirement where I don't need grid scrolling of carousel but a normal horizontal scrolling
