### ISSUE TITLE
Drag (Swipe) not working

### ISSUE THREAD

**Issue by EliezerB123** [uiuniversal/ngu-carousel#310]
Even using the demo provided, drag doesn't appear to be working, if I increase the items to "5".

(Swipe works fine, but if I drag, then release, it goes back to where it started.)

https://stackblitz.com/edit/ngu-carousel-ng6-jbeues?file=src%2Fapp%2Fapp.component.ts

**Comment by santoshyadavdev** [comment]
Thanks for stackblitz we will check it soon.

**Comment by alanfachim** [comment]
@Terrafire123 just set velocity: 0.2 in carouselTileConfig or less

**Comment by Terrafire123** [comment]
> @Terrafire123 just set velocity: 0.2 in carouselTileConfig or less

Thank you, alanfachim, but this doesn't actually solve anything.... Did you check the stackblitz? 

Perhaps I was unclear. To clarify, the error is that when you drag the slider, after you let go, it returns to its original location instead of snapping to the location that was dragged to.
