### ISSUE TITLE
How to prevent Data flickering

### ISSUE THREAD

**Issue by AntonGrekov** [uiuniversal/ngu-carousel#312]
In our project we have to always re-load data via api calls to keep data invalidated (right, now there is no other system for invalidating data). 

When i use ***ngFor** directive,  
````trackBy: trackByFn````
helps me prevent data flickering. Angular sees no difference in data and won't re-render items. 

With ngu-carousel, how can i achieve same functionality ? 
My data is synced via store, selectors.

Hm... may be i should try **distinctuntilchanged** or some similar rxjs functions.

**Comment by sheikalthaf** [comment]
@AntonGrekov we also support `trackby` function similar to ngFor. You can make use of it. I'll also update the readme with this example


```html
<ngu-carousel [inputs]="carouselBanner" (onMove)="onmoveFn($event)" [trackBy]="trackCarousel">
      <ngu-item NguCarouselItem class="bannerStyle">
        <h1>1</h1>
      </ngu-item>
</ngu-carousel>
```

```js
trackCarousel(_, item) {
    return item;
  }
```
