### ISSUE TITLE
 A dynamic import callback was not specified on 3.0.1 version

### ISSUE THREAD

**Issue by mohamedmk1** [uiuniversal/ngu-carousel#313]
Hi everybody,
I am facing  `A dynamic import callback was not specified ` issue when running test using jest.
Environment: 
-  Angular 10
-  Tyescript 4.0.2
- Jest 26.5.2

![image](https://user-images.githubusercontent.com/7072285/95452535-ad618e80-0969-11eb-8788-035ac2364791.png)

**Comment by mohamedmk1** [comment]
Hi, Have you a solution please ?

**Comment by arturovt** [comment]
Please, provide a minimal reproducible example. We are not able to divine what's happening on your side by looking at your screenshot.
