### ISSUE TITLE
Cannot read property length of undefined

### ISSUE THREAD

**Issue by AntonGrekov** [uiuniversal/ngu-carousel#316]
I am sorry, that might not be a bug, but i am stucked :( Was trying to google or find more info on that problem for 2 days.
I have an http get method in my project that returns an array of objects like this:
````
[ 
    {title: "Title1", id: 5, city: "City1"},
    {title: "Title2", id: 3, city: "City2"},
...
]
myStream$ = this.http.get('/api/getData')
````

http is a casual Angular Http Service that returns an observable.

I tried using pipe that slightly modifies that data and then use that Observable$ with ngu-carousel this way:
````
<div class="component__slider">
   <ngu-carousel
       #myCarousel
       [inputs]="carouselConfig"
       [dataSource]="myStream$ | async"
   >
````

I even simplified it, and tried using only http.get call to supply data to carousel. In either way i get "cannot read length of undefined". Why so? 

My other ngu-carousels in project use Store select observables and work great with async syntax as dataSource, even if i delay data loading from Store(to make it undefined for some seconds). Still, it's ok, ngu-carousel waits till data is emitted and then display slides, but it won't work that way with http.get method

**Comment by AntonGrekov** [comment]
I tried to initialize myStream$ with empty/non-empty array: **myStream$: Observable<any[]> = of([])**, and console.loged it's length at start(work as expected) to may be give something to ngu-carousel at start, but still same error

**Comment by PedroJesusRomeroOrtega** [comment]
I have the same error. Is there any workaround while this bug is getting fixed?

**Comment by PedroJesusRomeroOrtega** [comment]
The problem is in [this line](https://github.com/uiuniversal/ngu-carousel/blob/31f9221baf722eb56223254f9582db76ed7c824d/projects/ngu-carousel/src/lib/ngu-carousel/ngu-carousel.component.ts#L494) of _ngu-carousel.component.ts_, when using _http.get observable_ the datasource is undefined the first time.

As a workaround to avoid the error I subscribe to the observable before, instead of in the datasource property of _ngu-carousel_
``` diff
+<ng-container *ngIf="users$ | async as users">
-   <ngu-carousel #myCarousel [inputs]="carouselHttpConfig" [dataSource]="users$ | async">
+  <ngu-carousel #myCarousel [inputs]="carouselHttpConfig" [dataSource]="users">
      <ngu-item *nguCarouselDef="let item;">
        {{item.name}}
      </ngu-item>
   </ngu-carousel>
+</ng-container>
```
