### ISSUE TITLE
 Property 'inputs' is private and only accessible within class 'NguCarousel<T>'

### ISSUE THREAD

**Issue by JEpifanio** [uiuniversal/ngu-carousel#317]
Hey, guys!

I'm gettin this error with angular 10 strict mode:
![image](https://user-images.githubusercontent.com/55554505/97999289-bef35600-1db0-11eb-98a9-43c0c0848152.png)

Any workaround for this?

**Comment by JEpifanio** [comment]
Doing some more digging, here's what I found
![image](https://user-images.githubusercontent.com/55554505/98000165-cf580080-1db1-11eb-960f-a9edd16ddd14.png)

I think "private" has to go since it's a @input property

**Comment by JEpifanio** [comment]
Ok, I'll have to clean up this issue, BUT for those who are struggling with this and **DON'T WANT** to do some weird stuff like disabling AOT do this

![image](https://user-images.githubusercontent.com/55554505/98002717-78ebc180-1db3-11eb-8f52-0b07dd70b886.png)

**Comment by santoshyadavdev** [comment]
Available in 3.0.2 please try and let us know.

**Comment by NicholaAlkhouri** [comment]
@santoshyadavdev I had this problem previously, updating to 3.0.2 fixed the issue, thanks.
