### ISSUE TITLE
Is it Possible to Loop Around?

### ISSUE THREAD

**Issue by netlander** [uiuniversal/ngu-carousel#32]
Need a feature for looping around the images in the carousel, i.e. show images from beginning when reaching the last image, instead of sliding back through the entire list which is very annoying.

**Comment by netlander** [comment]
I guess not...

**Comment by sheikalthaf** [comment]
I'm trying to implement it. Before that I have to implement angular animations to slide smoothly and control individual items

**Comment by bitdistrict** [comment]
It would be very nice to have a feature like that, thanks!

**Comment by jonstieg** [comment]
there is now a `loop` property that can be set to `true` within NguCarouselConfig
