### ISSUE TITLE
Carousel configuration update dynamically

### ISSUE THREAD

**Issue by vm-hach** [uiuniversal/ngu-carousel#405]
Hi,
I need to update the touch property of my carousel configuration dynamically.
Modifying the property of the configuration, or even cloning the configuration to put a new reference to the carousel has no effect. Modifying the property directly throught the ViewChild object gives the same result.
What is very strange is that if I do it quite quickly after the view creation (<500ms), it is taken in account. If I do it after, it is not.

```
   public carouselTileConfig: NguCarouselConfig = {
      grid: { xs: 1, sm: 1, md: 1, lg: 1, all: 0 },
      slide: 3,
      speed: 250,
      point: {
         visible: true
      },
      load: 2,
      velocity: 0,
      touch: false,
      easing: 'cubic-bezier(0, 0, 0.2, 1)',
      loop: false
   };

   public slideSubject = new BehaviorSubject(true);

   ngOnInit() {
      this.slideSubject.subscribe(slide => {
         // this is well applied with the initial behavior subject value
         this.carouselTileConfig.touch = slide;
         this.carouselTileConfig = JSON.parse(JSON.stringify(this.carouselTileConfig));
         this.cdr.detectChanges();
      });

      // this has no effect !
      setTimeout(() => this.slideSubject.next(false), 2000);
   }
```

Is it a known bug? Is there any workaround?
Thanks for your help,

**Comment by santoshyadavdev** [comment]
It looks like something we dont support currently, will check if we can support this.
