### ISSUE TITLE
🐞 Missing `@angular/animations` in `peerDependencies`

### ISSUE THREAD

**Issue by Yberion** [uiuniversal/ngu-carousel#437]
**Describe the bug**

Missing `@angular/animations` in `package.json` from the lib.

- https://github.com/uiuniversal/ngu-carousel/blob/master/libs/ngu/carousel/package.json

I think it require to add `"@angular/animation": "^15.0.0"`

I tested with `7.0.0` and it works as expected.

**To Reproduce**

Try to use `7.1.1` on a fresh project which use latest Angular version (`15.2.7`).

```
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/animations@"15.0.2" from @ngu/carousel@7.1.1
npm ERR! node_modules/@ngu/carousel
npm ERR!   @ngu/carousel@"~7.1.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
```

**Expected behavior**

No error when installing the version `7.1.1`.

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Chrome
- Version: Latest

**Additional context**

Angular: `15.2.7`
carousel: `7.1.1`

Would you like to open a PR (Support will be provided):
[x] Yes
[ ] No

cc @santoshyadavdev, I can make a PR to fix the issue.

**Comment by santoshyadavdev** [comment]
Thank you for Reporting, yes please go ahead with the PR

**Comment by santoshyadavdev** [comment]
Released with 7.1.2

**Comment by Yberion** [comment]
Works fine!

I did set `zone.js` version in the lib which I think was not a good idea, I will make a PR to solve that or perhaps @arturovt can do that ?

- https://github.com/uiuniversal/ngu-carousel/blob/master/libs/ngu/carousel/package.json#L10

**Comment by santoshyadavdev** [comment]
Thank you Brandon, I can do this quickly

**Comment by Yberion** [comment]
That is awesome, thanks a lot Santos!
