### ISSUE TITLE
Grid size option is not able to use in latest version

### ISSUE THREAD

**Issue by azaddeveloper** [uiuniversal/ngu-carousel#445]
This is the [1.6.0-beta-1](https://www.npmjs.com/package/@ngu/carousel/v/1.6.0-beta-1) version and there was grid size option like this. **grid: { size: 2, offset: 15, isFixed: false, slide: 2 },**
I want to use this grid option in 3.01 version but it says Object literal may only specify known properties, and 'size' does not exist in type 'Transfrom'.

So pls see this why i am not able to use this 1.6.0 feature in latest version.

**Comment by santoshyadavdev** [comment]
Hi @azaddeveloper,

We are not supporting any previous versions. Please check the latest example and adjust your code accordingly.
