### ISSUE TITLE
Create release on npm for angular 16

### ISSUE THREAD

**Issue by Azzmurr** [uiuniversal/ngu-carousel#465]
**Is your feature request related to a problem? Please describe.**
In this repository, you updated the version of Angular to 16, but the latest release on npm 7.1.3 contains Angular 15, which creates problems when switching to version 16 of Angular

**Describe the solution you'd like**
Deploy new release from master to npm

**Describe alternatives you've considered**

**Additional context**

Would you like to open a PR (Support will be provided):
[ ] Yes
[ x] No

**Comment by santoshyadavdev** [comment]
Done with @ngu/carousel@7.2.0
