### ISSUE TITLE
Cannot read property 'Kbodyvalue' of undefined

### ISSUE THREAD

**Issue by yuyocp** [uiuniversal/ngu-carousel#49]
Hi, thanks in advance for your help. 
 I'm trying to use ngu-carousel  putting some small cards in every slider. I'm trying to build the cards dynamically with some info on it.  When I try to get the properties of one of the items in carouselTileOneItems, always  get the same error **Cannot read property 'Kbodyvalue' of undefined**. my goal is to assign the properties values to the inputs in the app-small-card component. 

    <ngu-carousel
                [inputs]="carouselOne"
                (carouselLoad)="carouselTileOneLoad()">
                  <ngu-item NguCarouselItem *ngFor="let tile of carouselTileOneItems; let i = index;" >

                      {{tile.Kbodyvalue}} 
                      <app-small-card 
                      [bodytext]="'Text'" 
                      [footertext]="'Footer'" 
                      [bodyvalue]="'10.5%'"  
                      [footercolor]="'card-footer bg-c-red'" 
                      [footerimg]="'fa fa-line-chart text-white f-16'" 
                      [footerfontcolor]="'text-white m-b-0'"
                      [bodyimg]="'fa fa-hand-o-down f-28'"
                      [bodyfontcolor]="'text-c-red'"
                      
                      ></app-small-card>
                  </ngu-item>
                
                  <button NguCarouselPrev class='leftRs'>&lt;</button>
                  <button NguCarouselNext class='rightRs'>&gt;</button>
             </ngu-carousel>

**Comment by sheikalthaf** [comment]
@yuyocp Hi,

I thing problem is not related to my carousel. If possible please create a stack blitz repo.

Thanks
