### ISSUE TITLE
Please update to angular 18

### ISSUE THREAD

**Issue by H-Luhrasbe** [uiuniversal/ngu-carousel#504]
Please update to angular 18.
Thanks

**Comment by guillaume-moreau** [comment]
Hello,

Any update on this issue ?
I see that version 18.0.0-rc.1 was pushed, and some commit have been made.

It's seems really close to be ready.

If I can help in any way, feel free to ask :)

Thank you !

**Comment by sheikalthaf** [comment]
@guillaume-moreau Yes, it is ready. Will release it today.

**Comment by sheikalthaf** [comment]
@guillaume-moreau v18 has been released yesterday, can you try and let me know.
