### ISSUE TITLE
Please put ngucarousel-inner back

### ISSUE THREAD

**Issue by dottodot** [uiuniversal/ngu-carousel#55]
On the beta version you have removed ngucarousel-inner and added `overflow:hidden` to the whole carousel. This makes it impossible to position the navigation outside of the container if desired.

**Comment by sheikalthaf** [comment]
@dottodot Hi,

Sorry for the late replay. I will add it back. I'm just testing

**Comment by cloughy** [comment]
hello 👋, 
I have exactly the same issue with the navigation.
Do you think it could be fixed ?
thanks for your work and help 👍
