### ISSUE TITLE
on changing orientation slide moves to 0th index instead of current index

### ISSUE THREAD

**Issue by KartikSagar007** [uiuniversal/ngu-carousel#6]
Hi,
on line no-264
/* change the active point in carousel /
NguCarouselComponent.prototype.carouselPointActiver = function () {
var i = Math.ceil(this.data.currentSlide / this.data.slideItems);***

While changing orientation of Mobile; here it is assigning my current slide to 0th index instead of current index. 

Please suggest on it.

**Comment by sheikalthaf** [comment]
@SagarBagga i already fixed this issue. i will investigate again

**Comment by SagarBagga** [comment]
i did some change in below two lines and it worked for me:

this.startAtIndex=this.index;
&
this.goToItem(this.startAtIndex);
