### ISSUE TITLE
CarouselComponent.html:1 ERROR TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by aliceFAN2017** [uiuniversal/ngu-carousel#84]
Hello sheikalthaf,
Could you please give some ideas on my below error when I use ngu-carousel, thank you!
ERROR TypeError: Object(...) is not a function
    at NguCarousel.webpackJsonp../node_modules/@ngu/carousel/fesm5/ngu-carousel.js.NguCarousel._observeRenderChanges (ngu-carousel.js:299)
    at NguCarousel.webpackJsonp../node_modules/@ngu/carousel/fesm5/ngu-carousel.js.NguCarousel.ngAfterContentInit (ngu-carousel.js:416)
    at callProviderLifecycles (core.js:12699)
    at callElementProvidersLifecycles (core.js:12673)
    at callLifecycleHooksChildrenFirst (core.js:12656)
    at checkAndUpdateView (core.js:13806)
    at callViewAction (core.js:14153)
    at execComponentViewsAction (core.js:14085)
    at checkAndUpdateView (core.js:13808)
    at callViewAction (core.js:14153)

**Comment by iiandrade** [comment]
I'm also getting this error after I upgraded to the latest version of the library. I have already updated the syntax of how to use the carousel.

For me, it looks like a bug with the rxjs lib, compatibility issues. I may be wrong!

Currently, I use Angular in version 5.2.11.

**Comment by iiandrade** [comment]
> Hello sheikalthaf,
> Could you please give some ideas on my below error when I use ngu-carousel, thank you!
> ERROR TypeError: Object(...) is not a function
> at NguCarousel.webpackJsonp../node_modules/@ngu/carousel/fesm5/ngu-carousel.js.NguCarousel._observeRenderChanges (ngu-carousel.js:299)
> at NguCarousel.webpackJsonp../node_modules/@ngu/carousel/fesm5/ngu-carousel.js.NguCarousel.ngAfterContentInit (ngu-carousel.js:416)
> at callProviderLifecycles (core.js:12699)
> at callElementProvidersLifecycles (core.js:12673)
> at callLifecycleHooksChildrenFirst (core.js:12656)
> at checkAndUpdateView (core.js:13806)
> at callViewAction (core.js:14153)
> at execComponentViewsAction (core.js:14085)
> at checkAndUpdateView (core.js:13808)
> at callViewAction (core.js:14153)

@aliceFAN2017 

What version of Angular are you using?

**Comment by sheikalthaf** [comment]
@aliceFAN2017 @iiandrade Hi,

Never faced this issue. Please have a stackblitz link with the issue.

Thanks

**Comment by aliceFAN2017** [comment]
> > Hello sheikalthaf,
> > Could you please give some ideas on my below error when I use ngu-carousel, thank you!
> > ERROR TypeError: Object(...) is not a function
> > at NguCarousel.webpackJsonp../node_modules/@ngu/carousel/fesm5/ngu-carousel.js.NguCarousel._observeRenderChanges (ngu-carousel.js:299)
> > at NguCarousel.webpackJsonp../node_modules/@ngu/carousel/fesm5/ngu-carousel.js.NguCarousel.ngAfterContentInit (ngu-carousel.js:416)
> > at callProviderLifecycles (core.js:12699)
> > at callElementProvidersLifecycles (core.js:12673)
> > at callLifecycleHooksChildrenFirst (core.js:12656)
> > at checkAndUpdateView (core.js:13806)
> > at callViewAction (core.js:14153)
> > at execComponentViewsAction (core.js:14085)
> > at checkAndUpdateView (core.js:13808)
> > at callViewAction (core.js:14153)
> 
> @aliceFAN2017
> 
> What version of Angular are you using?

Angular CLI: 1.7.2
Node: 8.11.3
OS: win32 ia32
Angular: 5.2.7

**Comment by kauegimenes** [comment]
I have the same issue

```
UpsertTaskComponent.html:30 ERROR TypeError: Object(...) is not a function
    at NguCarousel._observeRenderChanges (ngu-carousel.js:299)
    at NguCarousel.ngAfterContentInit (ngu-carousel.js:416)
    at callProviderLifecycles (core.js:12684)
    at callElementProvidersLifecycles (core.js:12658)
    at callLifecycleHooksChildrenFirst (core.js:12641)
    at checkAndUpdateView (core.js:13791)
    at callViewAction (core.js:14138)
    at execEmbeddedViewsAction (core.js:14096)
    at checkAndUpdateView (core.js:13788)
    at callViewAction (core.js:14138)
```

**Comment by iiandrade** [comment]
@kauegimenes @aliceFAN2017 

I was able to solve my problem by doing a downgrade in the library.

The step I took to resolve it was:

1. npm uninstall @ngu/carousel
2. npm install @ngu/carousel@1.4.8 --save-exact
3. I updated the syntax, modifying from new, to old. [read here](https://www.npmjs.com/package/@ngu/carousel/v/1.4.8)

In step 2 I put "--save-exact" to prevent automatic updates in the future.

**Comment by aliceFAN2017** [comment]
> @kauegimenes @aliceFAN2017
> 
> I was able to solve my problem by doing a downgrade in the library.
> 
> The step I took to resolve it was:
> 
> 1. npm uninstall @ngu/carousel
> 2. npm install @ngu/carousel@1.4.8 --save-exact
> 3. I updated the syntax, modifying from new, to old. [read here](https://www.npmjs.com/package/@ngu/carousel/v/1.4.8)
> 
> In step 2 I put "--save-exact" to prevent automatic updates in the future.
> 
> **_This should solve for now, until the other problem has been resolved._**

cool, solved, thank you!

**Comment by jproby** [comment]
Hi,
I am using Angular 5 and also have this error. But my problem is that I cannot downgrade as I use fixed width which doesn't work on mobile (crash browser) in @1.4.8.
Any solution or clue to solve this problem without downgrading ?

**Comment by sheikalthaf** [comment]
@jproby Hi,

Latest version of this carousel only supports angular version <= 6.

Thanks

**Comment by jproby** [comment]
@sheikalthaf I suppose you mean angular >= 6 ? So I am doomed !
How did you solved the browser crash with fixed width on mobile ? Anyway to patch the 1.4.8 version ?

**Comment by sheikalthaf** [comment]
@jproby Never faced any browser crash on mobile when using fixed width. Can you create a stackblitz with the issue?

**Comment by jproby** [comment]
It is the issue #21. By the way thanks for your work and help.

**Comment by sheikalthaf** [comment]
@jproby Yes it is fixed by properly following the component lifecycle hooks. Previously i called the initial function in OnInit.

**Comment by jproby** [comment]
Could you back port those changes to 1.4.8 ? Or I can fork repo and apply those changes.

**Comment by sheikalthaf** [comment]
@jproby But there is some major changes when compare to 1.4.8 and 1.5. Need to check the previous repo. If possible go back to previous commit of this repo and fix the lifecycle hooks calls. Thanks
